name: "Build and Push to dist for Cloudflare Pages"

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Deploy to dist branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Clone the repo into dist/, create dist branch if it doesn't exist
          REMOTE="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git clone "$REMOTE" dist
          cd dist
          git checkout dist || git checkout --orphan dist
          git rm -rf . || true
          cd ..

          # Copy built files into dist/
          cp -r _site/* dist/

          # Add .nojekyll so Cloudflare doesn't ignore underscore dirs
          touch dist/.nojekyll

          # Commit and push
          cd dist
          git add .
          git commit -m "Deploy on $(date -u)" || echo "Nothing to commit"
          git push --force "$REMOTE" dist
